-- Course names, teachers and rooms typed two ways (full-width spaces, Ａ１, Ⅰ, ｶﾅ) are saved one way,
-- as src/lib/text.ts cleanText does for new saves: NFKC for these characters, runs of spaces as one, trimmed.
-- Generated; one statement per group so no expression nests too deep.
UPDATE `shared_courses` SET `title` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`title`, 'ｦﾞ', 'ヺ'), 'ｳﾞ', 'ヴ'), 'ｶﾞ', 'ガ'), 'ｷﾞ', 'ギ'), 'ｸﾞ', 'グ'), 'ｹﾞ', 'ゲ'), 'ｺﾞ', 'ゴ'), 'ｻﾞ', 'ザ'), 'ｼﾞ', 'ジ'), 'ｽﾞ', 'ズ'), 'ｾﾞ', 'ゼ'), 'ｿﾞ', 'ゾ'), 'ﾀﾞ', 'ダ'), 'ﾁﾞ', 'ヂ'), 'ﾂﾞ', 'ヅ'), 'ﾃﾞ', 'デ'), 'ﾄﾞ', 'ド'), 'ﾊﾞ', 'バ'), 'ﾊﾟ', 'パ'), 'ﾋﾞ', 'ビ'), 'ﾋﾟ', 'ピ'), 'ﾌﾞ', 'ブ'), 'ﾌﾟ', 'プ'), 'ﾍﾞ', 'ベ'), 'ﾍﾟ', 'ペ'), 'ﾎﾞ', 'ボ'), 'ﾎﾟ', 'ポ'), 'ﾜﾞ', 'ヷ'), '！', '!'), '＂', '"'), '＃', '#'), '＄', '$'), '％', '%'), '＆', '&'), '＇', ''''), '（', '('), '）', ')'), '＊', '*'), '＋', '+'), '，', ',') WHERE instr(`title`, 'ｦﾞ') > 0 OR instr(`title`, 'ｳﾞ') > 0 OR instr(`title`, 'ｶﾞ') > 0 OR instr(`title`, 'ｷﾞ') > 0 OR instr(`title`, 'ｸﾞ') > 0 OR instr(`title`, 'ｹﾞ') > 0 OR instr(`title`, 'ｺﾞ') > 0 OR instr(`title`, 'ｻﾞ') > 0 OR instr(`title`, 'ｼﾞ') > 0 OR instr(`title`, 'ｽﾞ') > 0 OR instr(`title`, 'ｾﾞ') > 0 OR instr(`title`, 'ｿﾞ') > 0 OR instr(`title`, 'ﾀﾞ') > 0 OR instr(`title`, 'ﾁﾞ') > 0 OR instr(`title`, 'ﾂﾞ') > 0 OR instr(`title`, 'ﾃﾞ') > 0 OR instr(`title`, 'ﾄﾞ') > 0 OR instr(`title`, 'ﾊﾞ') > 0 OR instr(`title`, 'ﾊﾟ') > 0 OR instr(`title`, 'ﾋﾞ') > 0 OR instr(`title`, 'ﾋﾟ') > 0 OR instr(`title`, 'ﾌﾞ') > 0 OR instr(`title`, 'ﾌﾟ') > 0 OR instr(`title`, 'ﾍﾞ') > 0 OR instr(`title`, 'ﾍﾟ') > 0 OR instr(`title`, 'ﾎﾞ') > 0 OR instr(`title`, 'ﾎﾟ') > 0 OR instr(`title`, 'ﾜﾞ') > 0 OR instr(`title`, '！') > 0 OR instr(`title`, '＂') > 0 OR instr(`title`, '＃') > 0 OR instr(`title`, '＄') > 0 OR instr(`title`, '％') > 0 OR instr(`title`, '＆') > 0 OR instr(`title`, '＇') > 0 OR instr(`title`, '（') > 0 OR instr(`title`, '）') > 0 OR instr(`title`, '＊') > 0 OR instr(`title`, '＋') > 0 OR instr(`title`, '，') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`title`, '－', '-'), '．', '.'), '／', '/'), '０', '0'), '１', '1'), '２', '2'), '３', '3'), '４', '4'), '５', '5'), '６', '6'), '７', '7'), '８', '8'), '９', '9'), '：', ':'), '；', ';'), '＜', '<'), '＝', '='), '＞', '>'), '？', '?'), '＠', '@'), 'Ａ', 'A'), 'Ｂ', 'B'), 'Ｃ', 'C'), 'Ｄ', 'D'), 'Ｅ', 'E'), 'Ｆ', 'F'), 'Ｇ', 'G'), 'Ｈ', 'H'), 'Ｉ', 'I'), 'Ｊ', 'J'), 'Ｋ', 'K'), 'Ｌ', 'L'), 'Ｍ', 'M'), 'Ｎ', 'N'), 'Ｏ', 'O'), 'Ｐ', 'P'), 'Ｑ', 'Q'), 'Ｒ', 'R'), 'Ｓ', 'S'), 'Ｔ', 'T') WHERE instr(`title`, '－') > 0 OR instr(`title`, '．') > 0 OR instr(`title`, '／') > 0 OR instr(`title`, '０') > 0 OR instr(`title`, '１') > 0 OR instr(`title`, '２') > 0 OR instr(`title`, '３') > 0 OR instr(`title`, '４') > 0 OR instr(`title`, '５') > 0 OR instr(`title`, '６') > 0 OR instr(`title`, '７') > 0 OR instr(`title`, '８') > 0 OR instr(`title`, '９') > 0 OR instr(`title`, '：') > 0 OR instr(`title`, '；') > 0 OR instr(`title`, '＜') > 0 OR instr(`title`, '＝') > 0 OR instr(`title`, '＞') > 0 OR instr(`title`, '？') > 0 OR instr(`title`, '＠') > 0 OR instr(`title`, 'Ａ') > 0 OR instr(`title`, 'Ｂ') > 0 OR instr(`title`, 'Ｃ') > 0 OR instr(`title`, 'Ｄ') > 0 OR instr(`title`, 'Ｅ') > 0 OR instr(`title`, 'Ｆ') > 0 OR instr(`title`, 'Ｇ') > 0 OR instr(`title`, 'Ｈ') > 0 OR instr(`title`, 'Ｉ') > 0 OR instr(`title`, 'Ｊ') > 0 OR instr(`title`, 'Ｋ') > 0 OR instr(`title`, 'Ｌ') > 0 OR instr(`title`, 'Ｍ') > 0 OR instr(`title`, 'Ｎ') > 0 OR instr(`title`, 'Ｏ') > 0 OR instr(`title`, 'Ｐ') > 0 OR instr(`title`, 'Ｑ') > 0 OR instr(`title`, 'Ｒ') > 0 OR instr(`title`, 'Ｓ') > 0 OR instr(`title`, 'Ｔ') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`title`, 'Ｕ', 'U'), 'Ｖ', 'V'), 'Ｗ', 'W'), 'Ｘ', 'X'), 'Ｙ', 'Y'), 'Ｚ', 'Z'), '［', '['), '＼', '\'), '］', ']'), '＾', '^'), '＿', '_'), '｀', '`'), 'ａ', 'a'), 'ｂ', 'b'), 'ｃ', 'c'), 'ｄ', 'd'), 'ｅ', 'e'), 'ｆ', 'f'), 'ｇ', 'g'), 'ｈ', 'h'), 'ｉ', 'i'), 'ｊ', 'j'), 'ｋ', 'k'), 'ｌ', 'l'), 'ｍ', 'm'), 'ｎ', 'n'), 'ｏ', 'o'), 'ｐ', 'p'), 'ｑ', 'q'), 'ｒ', 'r'), 'ｓ', 's'), 'ｔ', 't'), 'ｕ', 'u'), 'ｖ', 'v'), 'ｗ', 'w'), 'ｘ', 'x'), 'ｙ', 'y'), 'ｚ', 'z'), '｛', '{'), '｜', '|') WHERE instr(`title`, 'Ｕ') > 0 OR instr(`title`, 'Ｖ') > 0 OR instr(`title`, 'Ｗ') > 0 OR instr(`title`, 'Ｘ') > 0 OR instr(`title`, 'Ｙ') > 0 OR instr(`title`, 'Ｚ') > 0 OR instr(`title`, '［') > 0 OR instr(`title`, '＼') > 0 OR instr(`title`, '］') > 0 OR instr(`title`, '＾') > 0 OR instr(`title`, '＿') > 0 OR instr(`title`, '｀') > 0 OR instr(`title`, 'ａ') > 0 OR instr(`title`, 'ｂ') > 0 OR instr(`title`, 'ｃ') > 0 OR instr(`title`, 'ｄ') > 0 OR instr(`title`, 'ｅ') > 0 OR instr(`title`, 'ｆ') > 0 OR instr(`title`, 'ｇ') > 0 OR instr(`title`, 'ｈ') > 0 OR instr(`title`, 'ｉ') > 0 OR instr(`title`, 'ｊ') > 0 OR instr(`title`, 'ｋ') > 0 OR instr(`title`, 'ｌ') > 0 OR instr(`title`, 'ｍ') > 0 OR instr(`title`, 'ｎ') > 0 OR instr(`title`, 'ｏ') > 0 OR instr(`title`, 'ｐ') > 0 OR instr(`title`, 'ｑ') > 0 OR instr(`title`, 'ｒ') > 0 OR instr(`title`, 'ｓ') > 0 OR instr(`title`, 'ｔ') > 0 OR instr(`title`, 'ｕ') > 0 OR instr(`title`, 'ｖ') > 0 OR instr(`title`, 'ｗ') > 0 OR instr(`title`, 'ｘ') > 0 OR instr(`title`, 'ｙ') > 0 OR instr(`title`, 'ｚ') > 0 OR instr(`title`, '｛') > 0 OR instr(`title`, '｜') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`title`, '｝', '}'), '～', '~'), '｟', '⦅'), '｠', '⦆'), '｡', '。'), '｢', '「'), '｣', '」'), '､', '、'), '･', '・'), 'ｦ', 'ヲ'), 'ｧ', 'ァ'), 'ｨ', 'ィ'), 'ｩ', 'ゥ'), 'ｪ', 'ェ'), 'ｫ', 'ォ'), 'ｬ', 'ャ'), 'ｭ', 'ュ'), 'ｮ', 'ョ'), 'ｯ', 'ッ'), 'ｰ', 'ー'), 'ｱ', 'ア'), 'ｲ', 'イ'), 'ｳ', 'ウ'), 'ｴ', 'エ'), 'ｵ', 'オ'), 'ｶ', 'カ'), 'ｷ', 'キ'), 'ｸ', 'ク'), 'ｹ', 'ケ'), 'ｺ', 'コ'), 'ｻ', 'サ'), 'ｼ', 'シ'), 'ｽ', 'ス'), 'ｾ', 'セ'), 'ｿ', 'ソ'), 'ﾀ', 'タ'), 'ﾁ', 'チ'), 'ﾂ', 'ツ'), 'ﾃ', 'テ'), 'ﾄ', 'ト') WHERE instr(`title`, '｝') > 0 OR instr(`title`, '～') > 0 OR instr(`title`, '｟') > 0 OR instr(`title`, '｠') > 0 OR instr(`title`, '｡') > 0 OR instr(`title`, '｢') > 0 OR instr(`title`, '｣') > 0 OR instr(`title`, '､') > 0 OR instr(`title`, '･') > 0 OR instr(`title`, 'ｦ') > 0 OR instr(`title`, 'ｧ') > 0 OR instr(`title`, 'ｨ') > 0 OR instr(`title`, 'ｩ') > 0 OR instr(`title`, 'ｪ') > 0 OR instr(`title`, 'ｫ') > 0 OR instr(`title`, 'ｬ') > 0 OR instr(`title`, 'ｭ') > 0 OR instr(`title`, 'ｮ') > 0 OR instr(`title`, 'ｯ') > 0 OR instr(`title`, 'ｰ') > 0 OR instr(`title`, 'ｱ') > 0 OR instr(`title`, 'ｲ') > 0 OR instr(`title`, 'ｳ') > 0 OR instr(`title`, 'ｴ') > 0 OR instr(`title`, 'ｵ') > 0 OR instr(`title`, 'ｶ') > 0 OR instr(`title`, 'ｷ') > 0 OR instr(`title`, 'ｸ') > 0 OR instr(`title`, 'ｹ') > 0 OR instr(`title`, 'ｺ') > 0 OR instr(`title`, 'ｻ') > 0 OR instr(`title`, 'ｼ') > 0 OR instr(`title`, 'ｽ') > 0 OR instr(`title`, 'ｾ') > 0 OR instr(`title`, 'ｿ') > 0 OR instr(`title`, 'ﾀ') > 0 OR instr(`title`, 'ﾁ') > 0 OR instr(`title`, 'ﾂ') > 0 OR instr(`title`, 'ﾃ') > 0 OR instr(`title`, 'ﾄ') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`title`, 'ﾅ', 'ナ'), 'ﾆ', 'ニ'), 'ﾇ', 'ヌ'), 'ﾈ', 'ネ'), 'ﾉ', 'ノ'), 'ﾊ', 'ハ'), 'ﾋ', 'ヒ'), 'ﾌ', 'フ'), 'ﾍ', 'ヘ'), 'ﾎ', 'ホ'), 'ﾏ', 'マ'), 'ﾐ', 'ミ'), 'ﾑ', 'ム'), 'ﾒ', 'メ'), 'ﾓ', 'モ'), 'ﾔ', 'ヤ'), 'ﾕ', 'ユ'), 'ﾖ', 'ヨ'), 'ﾗ', 'ラ'), 'ﾘ', 'リ'), 'ﾙ', 'ル'), 'ﾚ', 'レ'), 'ﾛ', 'ロ'), 'ﾜ', 'ワ'), 'ﾝ', 'ン'), 'ﾞ', '゙'), 'ﾟ', '゚'), 'ﾠ', 'ᅠ'), 'ﾡ', 'ᄀ'), 'ﾢ', 'ᄁ'), 'ﾣ', 'ᆪ'), 'ﾤ', 'ᄂ'), 'ﾥ', 'ᆬ'), 'ﾦ', 'ᆭ'), 'ﾧ', 'ᄃ'), 'ﾨ', 'ᄄ'), 'ﾩ', 'ᄅ'), 'ﾪ', 'ᆰ'), 'ﾫ', 'ᆱ'), 'ﾬ', 'ᆲ') WHERE instr(`title`, 'ﾅ') > 0 OR instr(`title`, 'ﾆ') > 0 OR instr(`title`, 'ﾇ') > 0 OR instr(`title`, 'ﾈ') > 0 OR instr(`title`, 'ﾉ') > 0 OR instr(`title`, 'ﾊ') > 0 OR instr(`title`, 'ﾋ') > 0 OR instr(`title`, 'ﾌ') > 0 OR instr(`title`, 'ﾍ') > 0 OR instr(`title`, 'ﾎ') > 0 OR instr(`title`, 'ﾏ') > 0 OR instr(`title`, 'ﾐ') > 0 OR instr(`title`, 'ﾑ') > 0 OR instr(`title`, 'ﾒ') > 0 OR instr(`title`, 'ﾓ') > 0 OR instr(`title`, 'ﾔ') > 0 OR instr(`title`, 'ﾕ') > 0 OR instr(`title`, 'ﾖ') > 0 OR instr(`title`, 'ﾗ') > 0 OR instr(`title`, 'ﾘ') > 0 OR instr(`title`, 'ﾙ') > 0 OR instr(`title`, 'ﾚ') > 0 OR instr(`title`, 'ﾛ') > 0 OR instr(`title`, 'ﾜ') > 0 OR instr(`title`, 'ﾝ') > 0 OR instr(`title`, 'ﾞ') > 0 OR instr(`title`, 'ﾟ') > 0 OR instr(`title`, 'ﾠ') > 0 OR instr(`title`, 'ﾡ') > 0 OR instr(`title`, 'ﾢ') > 0 OR instr(`title`, 'ﾣ') > 0 OR instr(`title`, 'ﾤ') > 0 OR instr(`title`, 'ﾥ') > 0 OR instr(`title`, 'ﾦ') > 0 OR instr(`title`, 'ﾧ') > 0 OR instr(`title`, 'ﾨ') > 0 OR instr(`title`, 'ﾩ') > 0 OR instr(`title`, 'ﾪ') > 0 OR instr(`title`, 'ﾫ') > 0 OR instr(`title`, 'ﾬ') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`title`, 'ﾭ', 'ᆳ'), 'ﾮ', 'ᆴ'), 'ﾯ', 'ᆵ'), 'ﾰ', 'ᄚ'), 'ﾱ', 'ᄆ'), 'ﾲ', 'ᄇ'), 'ﾳ', 'ᄈ'), 'ﾴ', 'ᄡ'), 'ﾵ', 'ᄉ'), 'ﾶ', 'ᄊ'), 'ﾷ', 'ᄋ'), 'ﾸ', 'ᄌ'), 'ﾹ', 'ᄍ'), 'ﾺ', 'ᄎ'), 'ﾻ', 'ᄏ'), 'ﾼ', 'ᄐ'), 'ﾽ', 'ᄑ'), 'ﾾ', 'ᄒ'), 'ￂ', 'ᅡ'), 'ￃ', 'ᅢ'), 'ￄ', 'ᅣ'), 'ￅ', 'ᅤ'), 'ￆ', 'ᅥ'), 'ￇ', 'ᅦ'), 'ￊ', 'ᅧ'), 'ￋ', 'ᅨ'), 'ￌ', 'ᅩ'), 'ￍ', 'ᅪ'), 'ￎ', 'ᅫ'), 'ￏ', 'ᅬ'), 'ￒ', 'ᅭ'), 'ￓ', 'ᅮ'), 'ￔ', 'ᅯ'), 'ￕ', 'ᅰ'), 'ￖ', 'ᅱ'), 'ￗ', 'ᅲ'), 'ￚ', 'ᅳ'), 'ￛ', 'ᅴ'), 'ￜ', 'ᅵ'), '￠', '¢') WHERE instr(`title`, 'ﾭ') > 0 OR instr(`title`, 'ﾮ') > 0 OR instr(`title`, 'ﾯ') > 0 OR instr(`title`, 'ﾰ') > 0 OR instr(`title`, 'ﾱ') > 0 OR instr(`title`, 'ﾲ') > 0 OR instr(`title`, 'ﾳ') > 0 OR instr(`title`, 'ﾴ') > 0 OR instr(`title`, 'ﾵ') > 0 OR instr(`title`, 'ﾶ') > 0 OR instr(`title`, 'ﾷ') > 0 OR instr(`title`, 'ﾸ') > 0 OR instr(`title`, 'ﾹ') > 0 OR instr(`title`, 'ﾺ') > 0 OR instr(`title`, 'ﾻ') > 0 OR instr(`title`, 'ﾼ') > 0 OR instr(`title`, 'ﾽ') > 0 OR instr(`title`, 'ﾾ') > 0 OR instr(`title`, 'ￂ') > 0 OR instr(`title`, 'ￃ') > 0 OR instr(`title`, 'ￄ') > 0 OR instr(`title`, 'ￅ') > 0 OR instr(`title`, 'ￆ') > 0 OR instr(`title`, 'ￇ') > 0 OR instr(`title`, 'ￊ') > 0 OR instr(`title`, 'ￋ') > 0 OR instr(`title`, 'ￌ') > 0 OR instr(`title`, 'ￍ') > 0 OR instr(`title`, 'ￎ') > 0 OR instr(`title`, 'ￏ') > 0 OR instr(`title`, 'ￒ') > 0 OR instr(`title`, 'ￓ') > 0 OR instr(`title`, 'ￔ') > 0 OR instr(`title`, 'ￕ') > 0 OR instr(`title`, 'ￖ') > 0 OR instr(`title`, 'ￗ') > 0 OR instr(`title`, 'ￚ') > 0 OR instr(`title`, 'ￛ') > 0 OR instr(`title`, 'ￜ') > 0 OR instr(`title`, '￠') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`title`, '￡', '£'), '￢', '¬'), '￣', ' ̄'), '￤', '¦'), '￥', '¥'), '￦', '₩'), '￨', '│'), '￩', '←'), '￪', '↑'), '￫', '→'), '￬', '↓'), '￭', '■'), '￮', '○'), 'Ⅰ', 'I'), 'Ⅱ', 'II'), 'Ⅲ', 'III'), 'Ⅳ', 'IV'), 'Ⅴ', 'V'), 'Ⅵ', 'VI'), 'Ⅶ', 'VII'), 'Ⅷ', 'VIII'), 'Ⅸ', 'IX'), 'Ⅹ', 'X'), 'Ⅺ', 'XI'), 'Ⅻ', 'XII'), 'Ⅼ', 'L'), 'Ⅽ', 'C'), 'Ⅾ', 'D'), 'Ⅿ', 'M'), 'ⅰ', 'i'), 'ⅱ', 'ii'), 'ⅲ', 'iii'), 'ⅳ', 'iv'), 'ⅴ', 'v'), 'ⅵ', 'vi'), 'ⅶ', 'vii'), 'ⅷ', 'viii'), 'ⅸ', 'ix'), 'ⅹ', 'x'), 'ⅺ', 'xi') WHERE instr(`title`, '￡') > 0 OR instr(`title`, '￢') > 0 OR instr(`title`, '￣') > 0 OR instr(`title`, '￤') > 0 OR instr(`title`, '￥') > 0 OR instr(`title`, '￦') > 0 OR instr(`title`, '￨') > 0 OR instr(`title`, '￩') > 0 OR instr(`title`, '￪') > 0 OR instr(`title`, '￫') > 0 OR instr(`title`, '￬') > 0 OR instr(`title`, '￭') > 0 OR instr(`title`, '￮') > 0 OR instr(`title`, 'Ⅰ') > 0 OR instr(`title`, 'Ⅱ') > 0 OR instr(`title`, 'Ⅲ') > 0 OR instr(`title`, 'Ⅳ') > 0 OR instr(`title`, 'Ⅴ') > 0 OR instr(`title`, 'Ⅵ') > 0 OR instr(`title`, 'Ⅶ') > 0 OR instr(`title`, 'Ⅷ') > 0 OR instr(`title`, 'Ⅸ') > 0 OR instr(`title`, 'Ⅹ') > 0 OR instr(`title`, 'Ⅺ') > 0 OR instr(`title`, 'Ⅻ') > 0 OR instr(`title`, 'Ⅼ') > 0 OR instr(`title`, 'Ⅽ') > 0 OR instr(`title`, 'Ⅾ') > 0 OR instr(`title`, 'Ⅿ') > 0 OR instr(`title`, 'ⅰ') > 0 OR instr(`title`, 'ⅱ') > 0 OR instr(`title`, 'ⅲ') > 0 OR instr(`title`, 'ⅳ') > 0 OR instr(`title`, 'ⅴ') > 0 OR instr(`title`, 'ⅵ') > 0 OR instr(`title`, 'ⅶ') > 0 OR instr(`title`, 'ⅷ') > 0 OR instr(`title`, 'ⅸ') > 0 OR instr(`title`, 'ⅹ') > 0 OR instr(`title`, 'ⅺ') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`title`, 'ⅻ', 'xii'), 'ⅼ', 'l'), 'ⅽ', 'c'), 'ⅾ', 'd'), 'ⅿ', 'm'), '①', '1'), '②', '2'), '③', '3'), '④', '4'), '⑤', '5'), '⑥', '6'), '⑦', '7'), '⑧', '8'), '⑨', '9'), '⑩', '10'), '⑪', '11'), '⑫', '12'), '⑬', '13'), '⑭', '14'), '⑮', '15'), '⑯', '16'), '⑰', '17'), '⑱', '18'), '⑲', '19'), '⑳', '20') WHERE instr(`title`, 'ⅻ') > 0 OR instr(`title`, 'ⅼ') > 0 OR instr(`title`, 'ⅽ') > 0 OR instr(`title`, 'ⅾ') > 0 OR instr(`title`, 'ⅿ') > 0 OR instr(`title`, '①') > 0 OR instr(`title`, '②') > 0 OR instr(`title`, '③') > 0 OR instr(`title`, '④') > 0 OR instr(`title`, '⑤') > 0 OR instr(`title`, '⑥') > 0 OR instr(`title`, '⑦') > 0 OR instr(`title`, '⑧') > 0 OR instr(`title`, '⑨') > 0 OR instr(`title`, '⑩') > 0 OR instr(`title`, '⑪') > 0 OR instr(`title`, '⑫') > 0 OR instr(`title`, '⑬') > 0 OR instr(`title`, '⑭') > 0 OR instr(`title`, '⑮') > 0 OR instr(`title`, '⑯') > 0 OR instr(`title`, '⑰') > 0 OR instr(`title`, '⑱') > 0 OR instr(`title`, '⑲') > 0 OR instr(`title`, '⑳') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`title`, char(9), ' '), char(10), ' '), char(11), ' '), char(12), ' '), char(13), ' '), char(160), ' '), char(8192), ' '), char(8193), ' '), char(8194), ' '), char(8195), ' '), char(8196), ' '), char(8197), ' '), char(8198), ' '), char(8199), ' '), char(8200), ' '), char(8201), ' '), char(8202), ' '), char(8232), ' '), char(8233), ' '), char(8239), ' '), char(8287), ' '), char(12288), ' ');
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(`title`, '  ', ' ') WHERE instr(`title`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(`title`, '  ', ' ') WHERE instr(`title`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(`title`, '  ', ' ') WHERE instr(`title`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(`title`, '  ', ' ') WHERE instr(`title`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(`title`, '  ', ' ') WHERE instr(`title`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = replace(`title`, '  ', ' ') WHERE instr(`title`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_courses` SET `title` = trim(`title`) WHERE `title` <> trim(`title`);
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, 'ｦﾞ', 'ヺ'), 'ｳﾞ', 'ヴ'), 'ｶﾞ', 'ガ'), 'ｷﾞ', 'ギ'), 'ｸﾞ', 'グ'), 'ｹﾞ', 'ゲ'), 'ｺﾞ', 'ゴ'), 'ｻﾞ', 'ザ'), 'ｼﾞ', 'ジ'), 'ｽﾞ', 'ズ'), 'ｾﾞ', 'ゼ'), 'ｿﾞ', 'ゾ'), 'ﾀﾞ', 'ダ'), 'ﾁﾞ', 'ヂ'), 'ﾂﾞ', 'ヅ'), 'ﾃﾞ', 'デ'), 'ﾄﾞ', 'ド'), 'ﾊﾞ', 'バ'), 'ﾊﾟ', 'パ'), 'ﾋﾞ', 'ビ'), 'ﾋﾟ', 'ピ'), 'ﾌﾞ', 'ブ'), 'ﾌﾟ', 'プ'), 'ﾍﾞ', 'ベ'), 'ﾍﾟ', 'ペ'), 'ﾎﾞ', 'ボ'), 'ﾎﾟ', 'ポ'), 'ﾜﾞ', 'ヷ'), '！', '!'), '＂', '"'), '＃', '#'), '＄', '$'), '％', '%'), '＆', '&'), '＇', ''''), '（', '('), '）', ')'), '＊', '*'), '＋', '+'), '，', ',') WHERE instr(`name`, 'ｦﾞ') > 0 OR instr(`name`, 'ｳﾞ') > 0 OR instr(`name`, 'ｶﾞ') > 0 OR instr(`name`, 'ｷﾞ') > 0 OR instr(`name`, 'ｸﾞ') > 0 OR instr(`name`, 'ｹﾞ') > 0 OR instr(`name`, 'ｺﾞ') > 0 OR instr(`name`, 'ｻﾞ') > 0 OR instr(`name`, 'ｼﾞ') > 0 OR instr(`name`, 'ｽﾞ') > 0 OR instr(`name`, 'ｾﾞ') > 0 OR instr(`name`, 'ｿﾞ') > 0 OR instr(`name`, 'ﾀﾞ') > 0 OR instr(`name`, 'ﾁﾞ') > 0 OR instr(`name`, 'ﾂﾞ') > 0 OR instr(`name`, 'ﾃﾞ') > 0 OR instr(`name`, 'ﾄﾞ') > 0 OR instr(`name`, 'ﾊﾞ') > 0 OR instr(`name`, 'ﾊﾟ') > 0 OR instr(`name`, 'ﾋﾞ') > 0 OR instr(`name`, 'ﾋﾟ') > 0 OR instr(`name`, 'ﾌﾞ') > 0 OR instr(`name`, 'ﾌﾟ') > 0 OR instr(`name`, 'ﾍﾞ') > 0 OR instr(`name`, 'ﾍﾟ') > 0 OR instr(`name`, 'ﾎﾞ') > 0 OR instr(`name`, 'ﾎﾟ') > 0 OR instr(`name`, 'ﾜﾞ') > 0 OR instr(`name`, '！') > 0 OR instr(`name`, '＂') > 0 OR instr(`name`, '＃') > 0 OR instr(`name`, '＄') > 0 OR instr(`name`, '％') > 0 OR instr(`name`, '＆') > 0 OR instr(`name`, '＇') > 0 OR instr(`name`, '（') > 0 OR instr(`name`, '）') > 0 OR instr(`name`, '＊') > 0 OR instr(`name`, '＋') > 0 OR instr(`name`, '，') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, '－', '-'), '．', '.'), '／', '/'), '０', '0'), '１', '1'), '２', '2'), '３', '3'), '４', '4'), '５', '5'), '６', '6'), '７', '7'), '８', '8'), '９', '9'), '：', ':'), '；', ';'), '＜', '<'), '＝', '='), '＞', '>'), '？', '?'), '＠', '@'), 'Ａ', 'A'), 'Ｂ', 'B'), 'Ｃ', 'C'), 'Ｄ', 'D'), 'Ｅ', 'E'), 'Ｆ', 'F'), 'Ｇ', 'G'), 'Ｈ', 'H'), 'Ｉ', 'I'), 'Ｊ', 'J'), 'Ｋ', 'K'), 'Ｌ', 'L'), 'Ｍ', 'M'), 'Ｎ', 'N'), 'Ｏ', 'O'), 'Ｐ', 'P'), 'Ｑ', 'Q'), 'Ｒ', 'R'), 'Ｓ', 'S'), 'Ｔ', 'T') WHERE instr(`name`, '－') > 0 OR instr(`name`, '．') > 0 OR instr(`name`, '／') > 0 OR instr(`name`, '０') > 0 OR instr(`name`, '１') > 0 OR instr(`name`, '２') > 0 OR instr(`name`, '３') > 0 OR instr(`name`, '４') > 0 OR instr(`name`, '５') > 0 OR instr(`name`, '６') > 0 OR instr(`name`, '７') > 0 OR instr(`name`, '８') > 0 OR instr(`name`, '９') > 0 OR instr(`name`, '：') > 0 OR instr(`name`, '；') > 0 OR instr(`name`, '＜') > 0 OR instr(`name`, '＝') > 0 OR instr(`name`, '＞') > 0 OR instr(`name`, '？') > 0 OR instr(`name`, '＠') > 0 OR instr(`name`, 'Ａ') > 0 OR instr(`name`, 'Ｂ') > 0 OR instr(`name`, 'Ｃ') > 0 OR instr(`name`, 'Ｄ') > 0 OR instr(`name`, 'Ｅ') > 0 OR instr(`name`, 'Ｆ') > 0 OR instr(`name`, 'Ｇ') > 0 OR instr(`name`, 'Ｈ') > 0 OR instr(`name`, 'Ｉ') > 0 OR instr(`name`, 'Ｊ') > 0 OR instr(`name`, 'Ｋ') > 0 OR instr(`name`, 'Ｌ') > 0 OR instr(`name`, 'Ｍ') > 0 OR instr(`name`, 'Ｎ') > 0 OR instr(`name`, 'Ｏ') > 0 OR instr(`name`, 'Ｐ') > 0 OR instr(`name`, 'Ｑ') > 0 OR instr(`name`, 'Ｒ') > 0 OR instr(`name`, 'Ｓ') > 0 OR instr(`name`, 'Ｔ') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, 'Ｕ', 'U'), 'Ｖ', 'V'), 'Ｗ', 'W'), 'Ｘ', 'X'), 'Ｙ', 'Y'), 'Ｚ', 'Z'), '［', '['), '＼', '\'), '］', ']'), '＾', '^'), '＿', '_'), '｀', '`'), 'ａ', 'a'), 'ｂ', 'b'), 'ｃ', 'c'), 'ｄ', 'd'), 'ｅ', 'e'), 'ｆ', 'f'), 'ｇ', 'g'), 'ｈ', 'h'), 'ｉ', 'i'), 'ｊ', 'j'), 'ｋ', 'k'), 'ｌ', 'l'), 'ｍ', 'm'), 'ｎ', 'n'), 'ｏ', 'o'), 'ｐ', 'p'), 'ｑ', 'q'), 'ｒ', 'r'), 'ｓ', 's'), 'ｔ', 't'), 'ｕ', 'u'), 'ｖ', 'v'), 'ｗ', 'w'), 'ｘ', 'x'), 'ｙ', 'y'), 'ｚ', 'z'), '｛', '{'), '｜', '|') WHERE instr(`name`, 'Ｕ') > 0 OR instr(`name`, 'Ｖ') > 0 OR instr(`name`, 'Ｗ') > 0 OR instr(`name`, 'Ｘ') > 0 OR instr(`name`, 'Ｙ') > 0 OR instr(`name`, 'Ｚ') > 0 OR instr(`name`, '［') > 0 OR instr(`name`, '＼') > 0 OR instr(`name`, '］') > 0 OR instr(`name`, '＾') > 0 OR instr(`name`, '＿') > 0 OR instr(`name`, '｀') > 0 OR instr(`name`, 'ａ') > 0 OR instr(`name`, 'ｂ') > 0 OR instr(`name`, 'ｃ') > 0 OR instr(`name`, 'ｄ') > 0 OR instr(`name`, 'ｅ') > 0 OR instr(`name`, 'ｆ') > 0 OR instr(`name`, 'ｇ') > 0 OR instr(`name`, 'ｈ') > 0 OR instr(`name`, 'ｉ') > 0 OR instr(`name`, 'ｊ') > 0 OR instr(`name`, 'ｋ') > 0 OR instr(`name`, 'ｌ') > 0 OR instr(`name`, 'ｍ') > 0 OR instr(`name`, 'ｎ') > 0 OR instr(`name`, 'ｏ') > 0 OR instr(`name`, 'ｐ') > 0 OR instr(`name`, 'ｑ') > 0 OR instr(`name`, 'ｒ') > 0 OR instr(`name`, 'ｓ') > 0 OR instr(`name`, 'ｔ') > 0 OR instr(`name`, 'ｕ') > 0 OR instr(`name`, 'ｖ') > 0 OR instr(`name`, 'ｗ') > 0 OR instr(`name`, 'ｘ') > 0 OR instr(`name`, 'ｙ') > 0 OR instr(`name`, 'ｚ') > 0 OR instr(`name`, '｛') > 0 OR instr(`name`, '｜') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, '｝', '}'), '～', '~'), '｟', '⦅'), '｠', '⦆'), '｡', '。'), '｢', '「'), '｣', '」'), '､', '、'), '･', '・'), 'ｦ', 'ヲ'), 'ｧ', 'ァ'), 'ｨ', 'ィ'), 'ｩ', 'ゥ'), 'ｪ', 'ェ'), 'ｫ', 'ォ'), 'ｬ', 'ャ'), 'ｭ', 'ュ'), 'ｮ', 'ョ'), 'ｯ', 'ッ'), 'ｰ', 'ー'), 'ｱ', 'ア'), 'ｲ', 'イ'), 'ｳ', 'ウ'), 'ｴ', 'エ'), 'ｵ', 'オ'), 'ｶ', 'カ'), 'ｷ', 'キ'), 'ｸ', 'ク'), 'ｹ', 'ケ'), 'ｺ', 'コ'), 'ｻ', 'サ'), 'ｼ', 'シ'), 'ｽ', 'ス'), 'ｾ', 'セ'), 'ｿ', 'ソ'), 'ﾀ', 'タ'), 'ﾁ', 'チ'), 'ﾂ', 'ツ'), 'ﾃ', 'テ'), 'ﾄ', 'ト') WHERE instr(`name`, '｝') > 0 OR instr(`name`, '～') > 0 OR instr(`name`, '｟') > 0 OR instr(`name`, '｠') > 0 OR instr(`name`, '｡') > 0 OR instr(`name`, '｢') > 0 OR instr(`name`, '｣') > 0 OR instr(`name`, '､') > 0 OR instr(`name`, '･') > 0 OR instr(`name`, 'ｦ') > 0 OR instr(`name`, 'ｧ') > 0 OR instr(`name`, 'ｨ') > 0 OR instr(`name`, 'ｩ') > 0 OR instr(`name`, 'ｪ') > 0 OR instr(`name`, 'ｫ') > 0 OR instr(`name`, 'ｬ') > 0 OR instr(`name`, 'ｭ') > 0 OR instr(`name`, 'ｮ') > 0 OR instr(`name`, 'ｯ') > 0 OR instr(`name`, 'ｰ') > 0 OR instr(`name`, 'ｱ') > 0 OR instr(`name`, 'ｲ') > 0 OR instr(`name`, 'ｳ') > 0 OR instr(`name`, 'ｴ') > 0 OR instr(`name`, 'ｵ') > 0 OR instr(`name`, 'ｶ') > 0 OR instr(`name`, 'ｷ') > 0 OR instr(`name`, 'ｸ') > 0 OR instr(`name`, 'ｹ') > 0 OR instr(`name`, 'ｺ') > 0 OR instr(`name`, 'ｻ') > 0 OR instr(`name`, 'ｼ') > 0 OR instr(`name`, 'ｽ') > 0 OR instr(`name`, 'ｾ') > 0 OR instr(`name`, 'ｿ') > 0 OR instr(`name`, 'ﾀ') > 0 OR instr(`name`, 'ﾁ') > 0 OR instr(`name`, 'ﾂ') > 0 OR instr(`name`, 'ﾃ') > 0 OR instr(`name`, 'ﾄ') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, 'ﾅ', 'ナ'), 'ﾆ', 'ニ'), 'ﾇ', 'ヌ'), 'ﾈ', 'ネ'), 'ﾉ', 'ノ'), 'ﾊ', 'ハ'), 'ﾋ', 'ヒ'), 'ﾌ', 'フ'), 'ﾍ', 'ヘ'), 'ﾎ', 'ホ'), 'ﾏ', 'マ'), 'ﾐ', 'ミ'), 'ﾑ', 'ム'), 'ﾒ', 'メ'), 'ﾓ', 'モ'), 'ﾔ', 'ヤ'), 'ﾕ', 'ユ'), 'ﾖ', 'ヨ'), 'ﾗ', 'ラ'), 'ﾘ', 'リ'), 'ﾙ', 'ル'), 'ﾚ', 'レ'), 'ﾛ', 'ロ'), 'ﾜ', 'ワ'), 'ﾝ', 'ン'), 'ﾞ', '゙'), 'ﾟ', '゚'), 'ﾠ', 'ᅠ'), 'ﾡ', 'ᄀ'), 'ﾢ', 'ᄁ'), 'ﾣ', 'ᆪ'), 'ﾤ', 'ᄂ'), 'ﾥ', 'ᆬ'), 'ﾦ', 'ᆭ'), 'ﾧ', 'ᄃ'), 'ﾨ', 'ᄄ'), 'ﾩ', 'ᄅ'), 'ﾪ', 'ᆰ'), 'ﾫ', 'ᆱ'), 'ﾬ', 'ᆲ') WHERE instr(`name`, 'ﾅ') > 0 OR instr(`name`, 'ﾆ') > 0 OR instr(`name`, 'ﾇ') > 0 OR instr(`name`, 'ﾈ') > 0 OR instr(`name`, 'ﾉ') > 0 OR instr(`name`, 'ﾊ') > 0 OR instr(`name`, 'ﾋ') > 0 OR instr(`name`, 'ﾌ') > 0 OR instr(`name`, 'ﾍ') > 0 OR instr(`name`, 'ﾎ') > 0 OR instr(`name`, 'ﾏ') > 0 OR instr(`name`, 'ﾐ') > 0 OR instr(`name`, 'ﾑ') > 0 OR instr(`name`, 'ﾒ') > 0 OR instr(`name`, 'ﾓ') > 0 OR instr(`name`, 'ﾔ') > 0 OR instr(`name`, 'ﾕ') > 0 OR instr(`name`, 'ﾖ') > 0 OR instr(`name`, 'ﾗ') > 0 OR instr(`name`, 'ﾘ') > 0 OR instr(`name`, 'ﾙ') > 0 OR instr(`name`, 'ﾚ') > 0 OR instr(`name`, 'ﾛ') > 0 OR instr(`name`, 'ﾜ') > 0 OR instr(`name`, 'ﾝ') > 0 OR instr(`name`, 'ﾞ') > 0 OR instr(`name`, 'ﾟ') > 0 OR instr(`name`, 'ﾠ') > 0 OR instr(`name`, 'ﾡ') > 0 OR instr(`name`, 'ﾢ') > 0 OR instr(`name`, 'ﾣ') > 0 OR instr(`name`, 'ﾤ') > 0 OR instr(`name`, 'ﾥ') > 0 OR instr(`name`, 'ﾦ') > 0 OR instr(`name`, 'ﾧ') > 0 OR instr(`name`, 'ﾨ') > 0 OR instr(`name`, 'ﾩ') > 0 OR instr(`name`, 'ﾪ') > 0 OR instr(`name`, 'ﾫ') > 0 OR instr(`name`, 'ﾬ') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, 'ﾭ', 'ᆳ'), 'ﾮ', 'ᆴ'), 'ﾯ', 'ᆵ'), 'ﾰ', 'ᄚ'), 'ﾱ', 'ᄆ'), 'ﾲ', 'ᄇ'), 'ﾳ', 'ᄈ'), 'ﾴ', 'ᄡ'), 'ﾵ', 'ᄉ'), 'ﾶ', 'ᄊ'), 'ﾷ', 'ᄋ'), 'ﾸ', 'ᄌ'), 'ﾹ', 'ᄍ'), 'ﾺ', 'ᄎ'), 'ﾻ', 'ᄏ'), 'ﾼ', 'ᄐ'), 'ﾽ', 'ᄑ'), 'ﾾ', 'ᄒ'), 'ￂ', 'ᅡ'), 'ￃ', 'ᅢ'), 'ￄ', 'ᅣ'), 'ￅ', 'ᅤ'), 'ￆ', 'ᅥ'), 'ￇ', 'ᅦ'), 'ￊ', 'ᅧ'), 'ￋ', 'ᅨ'), 'ￌ', 'ᅩ'), 'ￍ', 'ᅪ'), 'ￎ', 'ᅫ'), 'ￏ', 'ᅬ'), 'ￒ', 'ᅭ'), 'ￓ', 'ᅮ'), 'ￔ', 'ᅯ'), 'ￕ', 'ᅰ'), 'ￖ', 'ᅱ'), 'ￗ', 'ᅲ'), 'ￚ', 'ᅳ'), 'ￛ', 'ᅴ'), 'ￜ', 'ᅵ'), '￠', '¢') WHERE instr(`name`, 'ﾭ') > 0 OR instr(`name`, 'ﾮ') > 0 OR instr(`name`, 'ﾯ') > 0 OR instr(`name`, 'ﾰ') > 0 OR instr(`name`, 'ﾱ') > 0 OR instr(`name`, 'ﾲ') > 0 OR instr(`name`, 'ﾳ') > 0 OR instr(`name`, 'ﾴ') > 0 OR instr(`name`, 'ﾵ') > 0 OR instr(`name`, 'ﾶ') > 0 OR instr(`name`, 'ﾷ') > 0 OR instr(`name`, 'ﾸ') > 0 OR instr(`name`, 'ﾹ') > 0 OR instr(`name`, 'ﾺ') > 0 OR instr(`name`, 'ﾻ') > 0 OR instr(`name`, 'ﾼ') > 0 OR instr(`name`, 'ﾽ') > 0 OR instr(`name`, 'ﾾ') > 0 OR instr(`name`, 'ￂ') > 0 OR instr(`name`, 'ￃ') > 0 OR instr(`name`, 'ￄ') > 0 OR instr(`name`, 'ￅ') > 0 OR instr(`name`, 'ￆ') > 0 OR instr(`name`, 'ￇ') > 0 OR instr(`name`, 'ￊ') > 0 OR instr(`name`, 'ￋ') > 0 OR instr(`name`, 'ￌ') > 0 OR instr(`name`, 'ￍ') > 0 OR instr(`name`, 'ￎ') > 0 OR instr(`name`, 'ￏ') > 0 OR instr(`name`, 'ￒ') > 0 OR instr(`name`, 'ￓ') > 0 OR instr(`name`, 'ￔ') > 0 OR instr(`name`, 'ￕ') > 0 OR instr(`name`, 'ￖ') > 0 OR instr(`name`, 'ￗ') > 0 OR instr(`name`, 'ￚ') > 0 OR instr(`name`, 'ￛ') > 0 OR instr(`name`, 'ￜ') > 0 OR instr(`name`, '￠') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, '￡', '£'), '￢', '¬'), '￣', ' ̄'), '￤', '¦'), '￥', '¥'), '￦', '₩'), '￨', '│'), '￩', '←'), '￪', '↑'), '￫', '→'), '￬', '↓'), '￭', '■'), '￮', '○'), 'Ⅰ', 'I'), 'Ⅱ', 'II'), 'Ⅲ', 'III'), 'Ⅳ', 'IV'), 'Ⅴ', 'V'), 'Ⅵ', 'VI'), 'Ⅶ', 'VII'), 'Ⅷ', 'VIII'), 'Ⅸ', 'IX'), 'Ⅹ', 'X'), 'Ⅺ', 'XI'), 'Ⅻ', 'XII'), 'Ⅼ', 'L'), 'Ⅽ', 'C'), 'Ⅾ', 'D'), 'Ⅿ', 'M'), 'ⅰ', 'i'), 'ⅱ', 'ii'), 'ⅲ', 'iii'), 'ⅳ', 'iv'), 'ⅴ', 'v'), 'ⅵ', 'vi'), 'ⅶ', 'vii'), 'ⅷ', 'viii'), 'ⅸ', 'ix'), 'ⅹ', 'x'), 'ⅺ', 'xi') WHERE instr(`name`, '￡') > 0 OR instr(`name`, '￢') > 0 OR instr(`name`, '￣') > 0 OR instr(`name`, '￤') > 0 OR instr(`name`, '￥') > 0 OR instr(`name`, '￦') > 0 OR instr(`name`, '￨') > 0 OR instr(`name`, '￩') > 0 OR instr(`name`, '￪') > 0 OR instr(`name`, '￫') > 0 OR instr(`name`, '￬') > 0 OR instr(`name`, '￭') > 0 OR instr(`name`, '￮') > 0 OR instr(`name`, 'Ⅰ') > 0 OR instr(`name`, 'Ⅱ') > 0 OR instr(`name`, 'Ⅲ') > 0 OR instr(`name`, 'Ⅳ') > 0 OR instr(`name`, 'Ⅴ') > 0 OR instr(`name`, 'Ⅵ') > 0 OR instr(`name`, 'Ⅶ') > 0 OR instr(`name`, 'Ⅷ') > 0 OR instr(`name`, 'Ⅸ') > 0 OR instr(`name`, 'Ⅹ') > 0 OR instr(`name`, 'Ⅺ') > 0 OR instr(`name`, 'Ⅻ') > 0 OR instr(`name`, 'Ⅼ') > 0 OR instr(`name`, 'Ⅽ') > 0 OR instr(`name`, 'Ⅾ') > 0 OR instr(`name`, 'Ⅿ') > 0 OR instr(`name`, 'ⅰ') > 0 OR instr(`name`, 'ⅱ') > 0 OR instr(`name`, 'ⅲ') > 0 OR instr(`name`, 'ⅳ') > 0 OR instr(`name`, 'ⅴ') > 0 OR instr(`name`, 'ⅵ') > 0 OR instr(`name`, 'ⅶ') > 0 OR instr(`name`, 'ⅷ') > 0 OR instr(`name`, 'ⅸ') > 0 OR instr(`name`, 'ⅹ') > 0 OR instr(`name`, 'ⅺ') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, 'ⅻ', 'xii'), 'ⅼ', 'l'), 'ⅽ', 'c'), 'ⅾ', 'd'), 'ⅿ', 'm'), '①', '1'), '②', '2'), '③', '3'), '④', '4'), '⑤', '5'), '⑥', '6'), '⑦', '7'), '⑧', '8'), '⑨', '9'), '⑩', '10'), '⑪', '11'), '⑫', '12'), '⑬', '13'), '⑭', '14'), '⑮', '15'), '⑯', '16'), '⑰', '17'), '⑱', '18'), '⑲', '19'), '⑳', '20') WHERE instr(`name`, 'ⅻ') > 0 OR instr(`name`, 'ⅼ') > 0 OR instr(`name`, 'ⅽ') > 0 OR instr(`name`, 'ⅾ') > 0 OR instr(`name`, 'ⅿ') > 0 OR instr(`name`, '①') > 0 OR instr(`name`, '②') > 0 OR instr(`name`, '③') > 0 OR instr(`name`, '④') > 0 OR instr(`name`, '⑤') > 0 OR instr(`name`, '⑥') > 0 OR instr(`name`, '⑦') > 0 OR instr(`name`, '⑧') > 0 OR instr(`name`, '⑨') > 0 OR instr(`name`, '⑩') > 0 OR instr(`name`, '⑪') > 0 OR instr(`name`, '⑫') > 0 OR instr(`name`, '⑬') > 0 OR instr(`name`, '⑭') > 0 OR instr(`name`, '⑮') > 0 OR instr(`name`, '⑯') > 0 OR instr(`name`, '⑰') > 0 OR instr(`name`, '⑱') > 0 OR instr(`name`, '⑲') > 0 OR instr(`name`, '⑳') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, char(9), ' '), char(10), ' '), char(11), ' '), char(12), ' '), char(13), ' '), char(160), ' '), char(8192), ' '), char(8193), ' '), char(8194), ' '), char(8195), ' '), char(8196), ' '), char(8197), ' '), char(8198), ' '), char(8199), ' '), char(8200), ' '), char(8201), ' '), char(8202), ' '), char(8232), ' '), char(8233), ' '), char(8239), ' '), char(8287), ' '), char(12288), ' ');
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(`name`, '  ', ' ') WHERE instr(`name`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(`name`, '  ', ' ') WHERE instr(`name`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(`name`, '  ', ' ') WHERE instr(`name`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(`name`, '  ', ' ') WHERE instr(`name`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(`name`, '  ', ' ') WHERE instr(`name`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = replace(`name`, '  ', ' ') WHERE instr(`name`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_course_teachers` SET `name` = trim(`name`) WHERE `name` <> trim(`name`);
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`room`, 'ｦﾞ', 'ヺ'), 'ｳﾞ', 'ヴ'), 'ｶﾞ', 'ガ'), 'ｷﾞ', 'ギ'), 'ｸﾞ', 'グ'), 'ｹﾞ', 'ゲ'), 'ｺﾞ', 'ゴ'), 'ｻﾞ', 'ザ'), 'ｼﾞ', 'ジ'), 'ｽﾞ', 'ズ'), 'ｾﾞ', 'ゼ'), 'ｿﾞ', 'ゾ'), 'ﾀﾞ', 'ダ'), 'ﾁﾞ', 'ヂ'), 'ﾂﾞ', 'ヅ'), 'ﾃﾞ', 'デ'), 'ﾄﾞ', 'ド'), 'ﾊﾞ', 'バ'), 'ﾊﾟ', 'パ'), 'ﾋﾞ', 'ビ'), 'ﾋﾟ', 'ピ'), 'ﾌﾞ', 'ブ'), 'ﾌﾟ', 'プ'), 'ﾍﾞ', 'ベ'), 'ﾍﾟ', 'ペ'), 'ﾎﾞ', 'ボ'), 'ﾎﾟ', 'ポ'), 'ﾜﾞ', 'ヷ'), '！', '!'), '＂', '"'), '＃', '#'), '＄', '$'), '％', '%'), '＆', '&'), '＇', ''''), '（', '('), '）', ')'), '＊', '*'), '＋', '+'), '，', ',') WHERE instr(`room`, 'ｦﾞ') > 0 OR instr(`room`, 'ｳﾞ') > 0 OR instr(`room`, 'ｶﾞ') > 0 OR instr(`room`, 'ｷﾞ') > 0 OR instr(`room`, 'ｸﾞ') > 0 OR instr(`room`, 'ｹﾞ') > 0 OR instr(`room`, 'ｺﾞ') > 0 OR instr(`room`, 'ｻﾞ') > 0 OR instr(`room`, 'ｼﾞ') > 0 OR instr(`room`, 'ｽﾞ') > 0 OR instr(`room`, 'ｾﾞ') > 0 OR instr(`room`, 'ｿﾞ') > 0 OR instr(`room`, 'ﾀﾞ') > 0 OR instr(`room`, 'ﾁﾞ') > 0 OR instr(`room`, 'ﾂﾞ') > 0 OR instr(`room`, 'ﾃﾞ') > 0 OR instr(`room`, 'ﾄﾞ') > 0 OR instr(`room`, 'ﾊﾞ') > 0 OR instr(`room`, 'ﾊﾟ') > 0 OR instr(`room`, 'ﾋﾞ') > 0 OR instr(`room`, 'ﾋﾟ') > 0 OR instr(`room`, 'ﾌﾞ') > 0 OR instr(`room`, 'ﾌﾟ') > 0 OR instr(`room`, 'ﾍﾞ') > 0 OR instr(`room`, 'ﾍﾟ') > 0 OR instr(`room`, 'ﾎﾞ') > 0 OR instr(`room`, 'ﾎﾟ') > 0 OR instr(`room`, 'ﾜﾞ') > 0 OR instr(`room`, '！') > 0 OR instr(`room`, '＂') > 0 OR instr(`room`, '＃') > 0 OR instr(`room`, '＄') > 0 OR instr(`room`, '％') > 0 OR instr(`room`, '＆') > 0 OR instr(`room`, '＇') > 0 OR instr(`room`, '（') > 0 OR instr(`room`, '）') > 0 OR instr(`room`, '＊') > 0 OR instr(`room`, '＋') > 0 OR instr(`room`, '，') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`room`, '－', '-'), '．', '.'), '／', '/'), '０', '0'), '１', '1'), '２', '2'), '３', '3'), '４', '4'), '５', '5'), '６', '6'), '７', '7'), '８', '8'), '９', '9'), '：', ':'), '；', ';'), '＜', '<'), '＝', '='), '＞', '>'), '？', '?'), '＠', '@'), 'Ａ', 'A'), 'Ｂ', 'B'), 'Ｃ', 'C'), 'Ｄ', 'D'), 'Ｅ', 'E'), 'Ｆ', 'F'), 'Ｇ', 'G'), 'Ｈ', 'H'), 'Ｉ', 'I'), 'Ｊ', 'J'), 'Ｋ', 'K'), 'Ｌ', 'L'), 'Ｍ', 'M'), 'Ｎ', 'N'), 'Ｏ', 'O'), 'Ｐ', 'P'), 'Ｑ', 'Q'), 'Ｒ', 'R'), 'Ｓ', 'S'), 'Ｔ', 'T') WHERE instr(`room`, '－') > 0 OR instr(`room`, '．') > 0 OR instr(`room`, '／') > 0 OR instr(`room`, '０') > 0 OR instr(`room`, '１') > 0 OR instr(`room`, '２') > 0 OR instr(`room`, '３') > 0 OR instr(`room`, '４') > 0 OR instr(`room`, '５') > 0 OR instr(`room`, '６') > 0 OR instr(`room`, '７') > 0 OR instr(`room`, '８') > 0 OR instr(`room`, '９') > 0 OR instr(`room`, '：') > 0 OR instr(`room`, '；') > 0 OR instr(`room`, '＜') > 0 OR instr(`room`, '＝') > 0 OR instr(`room`, '＞') > 0 OR instr(`room`, '？') > 0 OR instr(`room`, '＠') > 0 OR instr(`room`, 'Ａ') > 0 OR instr(`room`, 'Ｂ') > 0 OR instr(`room`, 'Ｃ') > 0 OR instr(`room`, 'Ｄ') > 0 OR instr(`room`, 'Ｅ') > 0 OR instr(`room`, 'Ｆ') > 0 OR instr(`room`, 'Ｇ') > 0 OR instr(`room`, 'Ｈ') > 0 OR instr(`room`, 'Ｉ') > 0 OR instr(`room`, 'Ｊ') > 0 OR instr(`room`, 'Ｋ') > 0 OR instr(`room`, 'Ｌ') > 0 OR instr(`room`, 'Ｍ') > 0 OR instr(`room`, 'Ｎ') > 0 OR instr(`room`, 'Ｏ') > 0 OR instr(`room`, 'Ｐ') > 0 OR instr(`room`, 'Ｑ') > 0 OR instr(`room`, 'Ｒ') > 0 OR instr(`room`, 'Ｓ') > 0 OR instr(`room`, 'Ｔ') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`room`, 'Ｕ', 'U'), 'Ｖ', 'V'), 'Ｗ', 'W'), 'Ｘ', 'X'), 'Ｙ', 'Y'), 'Ｚ', 'Z'), '［', '['), '＼', '\'), '］', ']'), '＾', '^'), '＿', '_'), '｀', '`'), 'ａ', 'a'), 'ｂ', 'b'), 'ｃ', 'c'), 'ｄ', 'd'), 'ｅ', 'e'), 'ｆ', 'f'), 'ｇ', 'g'), 'ｈ', 'h'), 'ｉ', 'i'), 'ｊ', 'j'), 'ｋ', 'k'), 'ｌ', 'l'), 'ｍ', 'm'), 'ｎ', 'n'), 'ｏ', 'o'), 'ｐ', 'p'), 'ｑ', 'q'), 'ｒ', 'r'), 'ｓ', 's'), 'ｔ', 't'), 'ｕ', 'u'), 'ｖ', 'v'), 'ｗ', 'w'), 'ｘ', 'x'), 'ｙ', 'y'), 'ｚ', 'z'), '｛', '{'), '｜', '|') WHERE instr(`room`, 'Ｕ') > 0 OR instr(`room`, 'Ｖ') > 0 OR instr(`room`, 'Ｗ') > 0 OR instr(`room`, 'Ｘ') > 0 OR instr(`room`, 'Ｙ') > 0 OR instr(`room`, 'Ｚ') > 0 OR instr(`room`, '［') > 0 OR instr(`room`, '＼') > 0 OR instr(`room`, '］') > 0 OR instr(`room`, '＾') > 0 OR instr(`room`, '＿') > 0 OR instr(`room`, '｀') > 0 OR instr(`room`, 'ａ') > 0 OR instr(`room`, 'ｂ') > 0 OR instr(`room`, 'ｃ') > 0 OR instr(`room`, 'ｄ') > 0 OR instr(`room`, 'ｅ') > 0 OR instr(`room`, 'ｆ') > 0 OR instr(`room`, 'ｇ') > 0 OR instr(`room`, 'ｈ') > 0 OR instr(`room`, 'ｉ') > 0 OR instr(`room`, 'ｊ') > 0 OR instr(`room`, 'ｋ') > 0 OR instr(`room`, 'ｌ') > 0 OR instr(`room`, 'ｍ') > 0 OR instr(`room`, 'ｎ') > 0 OR instr(`room`, 'ｏ') > 0 OR instr(`room`, 'ｐ') > 0 OR instr(`room`, 'ｑ') > 0 OR instr(`room`, 'ｒ') > 0 OR instr(`room`, 'ｓ') > 0 OR instr(`room`, 'ｔ') > 0 OR instr(`room`, 'ｕ') > 0 OR instr(`room`, 'ｖ') > 0 OR instr(`room`, 'ｗ') > 0 OR instr(`room`, 'ｘ') > 0 OR instr(`room`, 'ｙ') > 0 OR instr(`room`, 'ｚ') > 0 OR instr(`room`, '｛') > 0 OR instr(`room`, '｜') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`room`, '｝', '}'), '～', '~'), '｟', '⦅'), '｠', '⦆'), '｡', '。'), '｢', '「'), '｣', '」'), '､', '、'), '･', '・'), 'ｦ', 'ヲ'), 'ｧ', 'ァ'), 'ｨ', 'ィ'), 'ｩ', 'ゥ'), 'ｪ', 'ェ'), 'ｫ', 'ォ'), 'ｬ', 'ャ'), 'ｭ', 'ュ'), 'ｮ', 'ョ'), 'ｯ', 'ッ'), 'ｰ', 'ー'), 'ｱ', 'ア'), 'ｲ', 'イ'), 'ｳ', 'ウ'), 'ｴ', 'エ'), 'ｵ', 'オ'), 'ｶ', 'カ'), 'ｷ', 'キ'), 'ｸ', 'ク'), 'ｹ', 'ケ'), 'ｺ', 'コ'), 'ｻ', 'サ'), 'ｼ', 'シ'), 'ｽ', 'ス'), 'ｾ', 'セ'), 'ｿ', 'ソ'), 'ﾀ', 'タ'), 'ﾁ', 'チ'), 'ﾂ', 'ツ'), 'ﾃ', 'テ'), 'ﾄ', 'ト') WHERE instr(`room`, '｝') > 0 OR instr(`room`, '～') > 0 OR instr(`room`, '｟') > 0 OR instr(`room`, '｠') > 0 OR instr(`room`, '｡') > 0 OR instr(`room`, '｢') > 0 OR instr(`room`, '｣') > 0 OR instr(`room`, '､') > 0 OR instr(`room`, '･') > 0 OR instr(`room`, 'ｦ') > 0 OR instr(`room`, 'ｧ') > 0 OR instr(`room`, 'ｨ') > 0 OR instr(`room`, 'ｩ') > 0 OR instr(`room`, 'ｪ') > 0 OR instr(`room`, 'ｫ') > 0 OR instr(`room`, 'ｬ') > 0 OR instr(`room`, 'ｭ') > 0 OR instr(`room`, 'ｮ') > 0 OR instr(`room`, 'ｯ') > 0 OR instr(`room`, 'ｰ') > 0 OR instr(`room`, 'ｱ') > 0 OR instr(`room`, 'ｲ') > 0 OR instr(`room`, 'ｳ') > 0 OR instr(`room`, 'ｴ') > 0 OR instr(`room`, 'ｵ') > 0 OR instr(`room`, 'ｶ') > 0 OR instr(`room`, 'ｷ') > 0 OR instr(`room`, 'ｸ') > 0 OR instr(`room`, 'ｹ') > 0 OR instr(`room`, 'ｺ') > 0 OR instr(`room`, 'ｻ') > 0 OR instr(`room`, 'ｼ') > 0 OR instr(`room`, 'ｽ') > 0 OR instr(`room`, 'ｾ') > 0 OR instr(`room`, 'ｿ') > 0 OR instr(`room`, 'ﾀ') > 0 OR instr(`room`, 'ﾁ') > 0 OR instr(`room`, 'ﾂ') > 0 OR instr(`room`, 'ﾃ') > 0 OR instr(`room`, 'ﾄ') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`room`, 'ﾅ', 'ナ'), 'ﾆ', 'ニ'), 'ﾇ', 'ヌ'), 'ﾈ', 'ネ'), 'ﾉ', 'ノ'), 'ﾊ', 'ハ'), 'ﾋ', 'ヒ'), 'ﾌ', 'フ'), 'ﾍ', 'ヘ'), 'ﾎ', 'ホ'), 'ﾏ', 'マ'), 'ﾐ', 'ミ'), 'ﾑ', 'ム'), 'ﾒ', 'メ'), 'ﾓ', 'モ'), 'ﾔ', 'ヤ'), 'ﾕ', 'ユ'), 'ﾖ', 'ヨ'), 'ﾗ', 'ラ'), 'ﾘ', 'リ'), 'ﾙ', 'ル'), 'ﾚ', 'レ'), 'ﾛ', 'ロ'), 'ﾜ', 'ワ'), 'ﾝ', 'ン'), 'ﾞ', '゙'), 'ﾟ', '゚'), 'ﾠ', 'ᅠ'), 'ﾡ', 'ᄀ'), 'ﾢ', 'ᄁ'), 'ﾣ', 'ᆪ'), 'ﾤ', 'ᄂ'), 'ﾥ', 'ᆬ'), 'ﾦ', 'ᆭ'), 'ﾧ', 'ᄃ'), 'ﾨ', 'ᄄ'), 'ﾩ', 'ᄅ'), 'ﾪ', 'ᆰ'), 'ﾫ', 'ᆱ'), 'ﾬ', 'ᆲ') WHERE instr(`room`, 'ﾅ') > 0 OR instr(`room`, 'ﾆ') > 0 OR instr(`room`, 'ﾇ') > 0 OR instr(`room`, 'ﾈ') > 0 OR instr(`room`, 'ﾉ') > 0 OR instr(`room`, 'ﾊ') > 0 OR instr(`room`, 'ﾋ') > 0 OR instr(`room`, 'ﾌ') > 0 OR instr(`room`, 'ﾍ') > 0 OR instr(`room`, 'ﾎ') > 0 OR instr(`room`, 'ﾏ') > 0 OR instr(`room`, 'ﾐ') > 0 OR instr(`room`, 'ﾑ') > 0 OR instr(`room`, 'ﾒ') > 0 OR instr(`room`, 'ﾓ') > 0 OR instr(`room`, 'ﾔ') > 0 OR instr(`room`, 'ﾕ') > 0 OR instr(`room`, 'ﾖ') > 0 OR instr(`room`, 'ﾗ') > 0 OR instr(`room`, 'ﾘ') > 0 OR instr(`room`, 'ﾙ') > 0 OR instr(`room`, 'ﾚ') > 0 OR instr(`room`, 'ﾛ') > 0 OR instr(`room`, 'ﾜ') > 0 OR instr(`room`, 'ﾝ') > 0 OR instr(`room`, 'ﾞ') > 0 OR instr(`room`, 'ﾟ') > 0 OR instr(`room`, 'ﾠ') > 0 OR instr(`room`, 'ﾡ') > 0 OR instr(`room`, 'ﾢ') > 0 OR instr(`room`, 'ﾣ') > 0 OR instr(`room`, 'ﾤ') > 0 OR instr(`room`, 'ﾥ') > 0 OR instr(`room`, 'ﾦ') > 0 OR instr(`room`, 'ﾧ') > 0 OR instr(`room`, 'ﾨ') > 0 OR instr(`room`, 'ﾩ') > 0 OR instr(`room`, 'ﾪ') > 0 OR instr(`room`, 'ﾫ') > 0 OR instr(`room`, 'ﾬ') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`room`, 'ﾭ', 'ᆳ'), 'ﾮ', 'ᆴ'), 'ﾯ', 'ᆵ'), 'ﾰ', 'ᄚ'), 'ﾱ', 'ᄆ'), 'ﾲ', 'ᄇ'), 'ﾳ', 'ᄈ'), 'ﾴ', 'ᄡ'), 'ﾵ', 'ᄉ'), 'ﾶ', 'ᄊ'), 'ﾷ', 'ᄋ'), 'ﾸ', 'ᄌ'), 'ﾹ', 'ᄍ'), 'ﾺ', 'ᄎ'), 'ﾻ', 'ᄏ'), 'ﾼ', 'ᄐ'), 'ﾽ', 'ᄑ'), 'ﾾ', 'ᄒ'), 'ￂ', 'ᅡ'), 'ￃ', 'ᅢ'), 'ￄ', 'ᅣ'), 'ￅ', 'ᅤ'), 'ￆ', 'ᅥ'), 'ￇ', 'ᅦ'), 'ￊ', 'ᅧ'), 'ￋ', 'ᅨ'), 'ￌ', 'ᅩ'), 'ￍ', 'ᅪ'), 'ￎ', 'ᅫ'), 'ￏ', 'ᅬ'), 'ￒ', 'ᅭ'), 'ￓ', 'ᅮ'), 'ￔ', 'ᅯ'), 'ￕ', 'ᅰ'), 'ￖ', 'ᅱ'), 'ￗ', 'ᅲ'), 'ￚ', 'ᅳ'), 'ￛ', 'ᅴ'), 'ￜ', 'ᅵ'), '￠', '¢') WHERE instr(`room`, 'ﾭ') > 0 OR instr(`room`, 'ﾮ') > 0 OR instr(`room`, 'ﾯ') > 0 OR instr(`room`, 'ﾰ') > 0 OR instr(`room`, 'ﾱ') > 0 OR instr(`room`, 'ﾲ') > 0 OR instr(`room`, 'ﾳ') > 0 OR instr(`room`, 'ﾴ') > 0 OR instr(`room`, 'ﾵ') > 0 OR instr(`room`, 'ﾶ') > 0 OR instr(`room`, 'ﾷ') > 0 OR instr(`room`, 'ﾸ') > 0 OR instr(`room`, 'ﾹ') > 0 OR instr(`room`, 'ﾺ') > 0 OR instr(`room`, 'ﾻ') > 0 OR instr(`room`, 'ﾼ') > 0 OR instr(`room`, 'ﾽ') > 0 OR instr(`room`, 'ﾾ') > 0 OR instr(`room`, 'ￂ') > 0 OR instr(`room`, 'ￃ') > 0 OR instr(`room`, 'ￄ') > 0 OR instr(`room`, 'ￅ') > 0 OR instr(`room`, 'ￆ') > 0 OR instr(`room`, 'ￇ') > 0 OR instr(`room`, 'ￊ') > 0 OR instr(`room`, 'ￋ') > 0 OR instr(`room`, 'ￌ') > 0 OR instr(`room`, 'ￍ') > 0 OR instr(`room`, 'ￎ') > 0 OR instr(`room`, 'ￏ') > 0 OR instr(`room`, 'ￒ') > 0 OR instr(`room`, 'ￓ') > 0 OR instr(`room`, 'ￔ') > 0 OR instr(`room`, 'ￕ') > 0 OR instr(`room`, 'ￖ') > 0 OR instr(`room`, 'ￗ') > 0 OR instr(`room`, 'ￚ') > 0 OR instr(`room`, 'ￛ') > 0 OR instr(`room`, 'ￜ') > 0 OR instr(`room`, '￠') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`room`, '￡', '£'), '￢', '¬'), '￣', ' ̄'), '￤', '¦'), '￥', '¥'), '￦', '₩'), '￨', '│'), '￩', '←'), '￪', '↑'), '￫', '→'), '￬', '↓'), '￭', '■'), '￮', '○'), 'Ⅰ', 'I'), 'Ⅱ', 'II'), 'Ⅲ', 'III'), 'Ⅳ', 'IV'), 'Ⅴ', 'V'), 'Ⅵ', 'VI'), 'Ⅶ', 'VII'), 'Ⅷ', 'VIII'), 'Ⅸ', 'IX'), 'Ⅹ', 'X'), 'Ⅺ', 'XI'), 'Ⅻ', 'XII'), 'Ⅼ', 'L'), 'Ⅽ', 'C'), 'Ⅾ', 'D'), 'Ⅿ', 'M'), 'ⅰ', 'i'), 'ⅱ', 'ii'), 'ⅲ', 'iii'), 'ⅳ', 'iv'), 'ⅴ', 'v'), 'ⅵ', 'vi'), 'ⅶ', 'vii'), 'ⅷ', 'viii'), 'ⅸ', 'ix'), 'ⅹ', 'x'), 'ⅺ', 'xi') WHERE instr(`room`, '￡') > 0 OR instr(`room`, '￢') > 0 OR instr(`room`, '￣') > 0 OR instr(`room`, '￤') > 0 OR instr(`room`, '￥') > 0 OR instr(`room`, '￦') > 0 OR instr(`room`, '￨') > 0 OR instr(`room`, '￩') > 0 OR instr(`room`, '￪') > 0 OR instr(`room`, '￫') > 0 OR instr(`room`, '￬') > 0 OR instr(`room`, '￭') > 0 OR instr(`room`, '￮') > 0 OR instr(`room`, 'Ⅰ') > 0 OR instr(`room`, 'Ⅱ') > 0 OR instr(`room`, 'Ⅲ') > 0 OR instr(`room`, 'Ⅳ') > 0 OR instr(`room`, 'Ⅴ') > 0 OR instr(`room`, 'Ⅵ') > 0 OR instr(`room`, 'Ⅶ') > 0 OR instr(`room`, 'Ⅷ') > 0 OR instr(`room`, 'Ⅸ') > 0 OR instr(`room`, 'Ⅹ') > 0 OR instr(`room`, 'Ⅺ') > 0 OR instr(`room`, 'Ⅻ') > 0 OR instr(`room`, 'Ⅼ') > 0 OR instr(`room`, 'Ⅽ') > 0 OR instr(`room`, 'Ⅾ') > 0 OR instr(`room`, 'Ⅿ') > 0 OR instr(`room`, 'ⅰ') > 0 OR instr(`room`, 'ⅱ') > 0 OR instr(`room`, 'ⅲ') > 0 OR instr(`room`, 'ⅳ') > 0 OR instr(`room`, 'ⅴ') > 0 OR instr(`room`, 'ⅵ') > 0 OR instr(`room`, 'ⅶ') > 0 OR instr(`room`, 'ⅷ') > 0 OR instr(`room`, 'ⅸ') > 0 OR instr(`room`, 'ⅹ') > 0 OR instr(`room`, 'ⅺ') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`room`, 'ⅻ', 'xii'), 'ⅼ', 'l'), 'ⅽ', 'c'), 'ⅾ', 'd'), 'ⅿ', 'm'), '①', '1'), '②', '2'), '③', '3'), '④', '4'), '⑤', '5'), '⑥', '6'), '⑦', '7'), '⑧', '8'), '⑨', '9'), '⑩', '10'), '⑪', '11'), '⑫', '12'), '⑬', '13'), '⑭', '14'), '⑮', '15'), '⑯', '16'), '⑰', '17'), '⑱', '18'), '⑲', '19'), '⑳', '20') WHERE instr(`room`, 'ⅻ') > 0 OR instr(`room`, 'ⅼ') > 0 OR instr(`room`, 'ⅽ') > 0 OR instr(`room`, 'ⅾ') > 0 OR instr(`room`, 'ⅿ') > 0 OR instr(`room`, '①') > 0 OR instr(`room`, '②') > 0 OR instr(`room`, '③') > 0 OR instr(`room`, '④') > 0 OR instr(`room`, '⑤') > 0 OR instr(`room`, '⑥') > 0 OR instr(`room`, '⑦') > 0 OR instr(`room`, '⑧') > 0 OR instr(`room`, '⑨') > 0 OR instr(`room`, '⑩') > 0 OR instr(`room`, '⑪') > 0 OR instr(`room`, '⑫') > 0 OR instr(`room`, '⑬') > 0 OR instr(`room`, '⑭') > 0 OR instr(`room`, '⑮') > 0 OR instr(`room`, '⑯') > 0 OR instr(`room`, '⑰') > 0 OR instr(`room`, '⑱') > 0 OR instr(`room`, '⑲') > 0 OR instr(`room`, '⑳') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`room`, char(9), ' '), char(10), ' '), char(11), ' '), char(12), ' '), char(13), ' '), char(160), ' '), char(8192), ' '), char(8193), ' '), char(8194), ' '), char(8195), ' '), char(8196), ' '), char(8197), ' '), char(8198), ' '), char(8199), ' '), char(8200), ' '), char(8201), ' '), char(8202), ' '), char(8232), ' '), char(8233), ' '), char(8239), ' '), char(8287), ' '), char(12288), ' ');
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(`room`, '  ', ' ') WHERE instr(`room`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(`room`, '  ', ' ') WHERE instr(`room`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(`room`, '  ', ' ') WHERE instr(`room`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(`room`, '  ', ' ') WHERE instr(`room`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(`room`, '  ', ' ') WHERE instr(`room`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = replace(`room`, '  ', ' ') WHERE instr(`room`, '  ') > 0;
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = trim(`room`) WHERE `room` <> trim(`room`);
--> statement-breakpoint
UPDATE `shared_course_slots` SET `room` = NULL WHERE `room` = '';
--> statement-breakpoint
DELETE FROM `shared_course_teachers` WHERE `name` = '';
--> statement-breakpoint
-- A teacher listed twice once the names match is kept once
DELETE FROM `shared_course_teachers` WHERE rowid NOT IN (SELECT min(rowid) FROM `shared_course_teachers` GROUP BY `shared_course_id`, `name`);

